=head1 NAME

clds - close open file descriptors and execute a command

=head1 SYNOPSIS

 clfds [-k <df>[,<fd>*]] <cmd> <arg>*

=head1 DESCRIPTION

Close open file descriptors and execute C<cmd>. By default, only the
standard I/O file descriptors 0, 1 and 2 are left open. The -k option
(for I<keep>) can be used to prevent other open file descriptors from
being closed.

=head1 OPTIONS

=over

=item B<-k I<fd[,fd*]>>

Comma-separated list of file descriptors which should also remain open.

=back
